Repository tazama-lf/event-flow, pull requests merged in 2024-10, with the labels that each got.

#20 feat: Env/validation
  .env.template
  .npmrc
  Dockerfile
  __tests__/unit/efrup.test.ts
  jest.testEnv.ts
  package-lock.json
  package.json
  src/apm.ts
  src/config.ts
  src/index.ts
  src/logic.service.ts
Labels: enhancement

#26 refactor: split cache options env vars
  .env.template
  Dockerfile
  __tests__/unit/efrup.test.ts
  jest.testEnv.ts
  package-lock.json
  package.json
  src/config.ts
  src/index.ts
  src/logic.service.ts
Labels: refactor

#25 fix: Issue 227 Add Tazama into to LICENSE
  LICENSE
Labels: bug

#28 refactor: encapsulate environment variables
  __tests__/unit/efrup.test.ts
  package-lock.json
  package.json
  src/apm.ts
  src/config.ts
  src/index.ts
  src/logic.service.ts
Labels: refactor

#31 feat: add multi-currency support in datacahce
  README.md
  jest.testEnv.ts
  package-lock.json
  package.json
Labels: enhancement
